[build]
  command = "CI= npm run build"
  publish = ".next"

[functions]
  external_node_modules = ["@prisma/client", ".prisma/client"]

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200